id: P9AC281AF
initial_creation_type: input
source_metadata:
  title: Lhatsün Namkha Jigme Series
  language: es
  description: 'Texts associated with the famous yogi Lhatsün Namkha Jigme (lha btsun
    nam mkha'' ''jigs med, 1597–1650), who is credited with ''opening the hidden land''
    of Sikkim:'
  volume:
    1389f4a2bada4e7f91c7f7b3a3506944:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    91047509232d4f52a515cc6d9f82e677:
      title: Summoning Prosperity
      parent: Prayers and Practices
    aba7da8639b148359b98cc8ba8b41d31:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Sang Offering
    344fa5a7a2004eacbeab43816bb1dc62:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Sang Offering
    09bcdc0859ce4397802ffeac36b7fab3:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
created_at: '2022-03-01T00:35:25.497173'
last_modified_at: '2022-03-01T00:35:25.497176'
